### ISSUE TITLE
Registration toggle needs to be checked in the backend

### ISSUE THREAD

**Issue by qutax** [pace-running/pace3#88]
While the registration toggle deactivates the form to register a new runner, it is still possible to send requests to the API and successfully register.

**Comment by nvinogradova** [comment]
![Screenshot 2023-06-21 at 09 11 47](https://github.com/pace-running/pace3/assets/110037839/4e6b4d48-7225-4ebe-b0de-753dda1c7db6)

**Comment by nvinogradova** [comment]
When the toggles are deactivated on the changeTheme page and changes are saved, I am rerouted to the Admin page. But if I am going back to the changeTheme page, the toggles are still active. I need to refresh the browser tab so that to see the updates. #98 is created to save the updates automatically for the user
